config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'calendar#day'
  get 'home', to: 'pages#home'

  resource :mood, only: [:new, :create, :edit, :show, :update]
  resolve('Mood') { [:mood] }

  resources :events, only: [:index, :new, :create, :edit, :update, :destroy]

  get 'stats', to: 'pages#stats'
  get 'month', to: 'calendar#month'
  get 'day', to: 'calendar#day'
  get 'set_theme', to: 'application#set_theme'
end

app/models/mood.rb
class Mood < ApplicationRecord
  belongs_to :user
  validates :rating, numericality: { in: 1..6 }, presence: true, allow_blank: false
  validates :journal_entry, presence: true, allow_blank: false
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: %i[show new edit]

  def show
    @date = Date.parse(date_params)
    if @mood.nil?
      redirect_to new_mood_path(date: @date)
    else
      @mood_rating = @mood.rating
      display_emoji
    end
  end

  def new
    @date = Date.parse(params[:date])
    @mood = Mood.new(date: @date)
  end

  def create
    params[:date] ||= params[:mood][:date]
    @mood = Mood.new(mood_params)
    @mood.user = current_user
    @mood.save
    if @mood.save
      redirect_to mood_path(date: @mood.date)
    else
      render :new
    end
  end

  def edit; end

  def update
    @mood = Mood.find(mood_params[:id])
    @mood.update(mood_params)
    @mood.save
    if @mood.save
      redirect_to mood_path(date: @mood.date)
    else
      render :new
    end
  end

  private

  def mood_params
    params.require(:mood).permit(:rating, :journal_entry, :date, :id)
  end

  def date_params
    params.require(:date)
  end

  def set_mood
    @mood = current_user.moods.find_by(date: Date.parse(date_params))
  end
end

app/views/moods/_form.html.erb
<div class="container" data-controller="mood">
  <%= simple_form_for @mood do |p| %>
    <div class="mood-form">
      <%= p.input :rating, as: :radio_buttons,
                          collection: [['1', '😢'],
                                       ['2', '💩'],
                                       ['3', '😡'],
                                       ['4', '😐'],
                                       ['5', '😊'],
                                       ['6', '😀']],
                          label_method: :second,
                          value_method: :first,
                          wrapper_html: { class: 'radio-buttons' },
                          input_html: { data: { action: 'change->mood#enable' } },
                          required: true,
                          error: "Don't fool yourself... Tell us how you feel." %>
    </div>
    <%= p.input :journal_entry, required: true,
                                error: "This does not seem right.",
                                input_html: { data: { action: 'keyup->mood#enable' } } %>
    <%= p.hidden_field :id, value: @mood.id %>
    <%= p.hidden_field :date, value: @mood.date %>
    <!-- Figure out if emoji and journal_entry have input to enable btn again -->
    <!-- Stimulus Controller or normal JS -->
    <div data-mood-target="output">
      <%= p.button :submit, "Submit Mood",
                  class: "btn-gradient my-3",
                  disabled: true %>
    </div>
  <% end %>
  <%= link_to "Cancel", mood_path(date: (params[:date])) if action_name == "edit"%>
</div>

app/views/moods/_tabs.html.erb
<div class="container moon-nav">
  <%= link_to day_path(date: params[:date]) do %>
      <i class="fas fa-circle"> </i>
  <% end %>
  <i class="fas fa-circle target"></i>
  <%= link_to events_path(date: params[:date]) do %>
    <i class="fas fa-circle"></i>
  <% end %>
</div>

app/views/moods/edit.html.erb
<div class="container form-inputs">
  <h3>Make changes to your mood:</h3>
  <%= render "form", mood: @mood %>
</div>

app/views/moods/new.html.erb
<div class="form-inputs">
  <div class="date-navigation">
    <% if params[:date] %>
      <%= link_to mood_path(date: (params[:date].to_date - 1)) do %>
        <i class="fas fa-arrow-left"> </i>
      <% end %>
      <h1 class="date-today my-3"><%= params[:date].to_date.strftime("%b %d") %></h1>
      <%= link_to mood_path(date: (params[:date].to_date + 1)) do %>
        <i class="fas fa-arrow-right"> </i>
      <% end %>
    <% end %>
  </div>
  <!-- If you try to create empty Mood errors pops up -->
  <% if params.dig(:date)&.to_date <= Date.today %>
    <!-- Problem persists without conditional (no params[:date] to :new) -->
    <%= render "form", mood: @mood %>
  <% else %>
    <p style="text-align: center; margin: 50px 0"><em>You can't really predict your mood in the future, can you? 🔮</em></p>
  <% end %>
  <%= render "tabs" %>
</div>

app/views/moods/show.html.erb
<div class="container page" style="margin-bottom: 80px">
  <div class="date-navigation">
    <% if params[:date] %>
      <%= link_to mood_path(date: (params[:date].to_date - 1)) do %>
        <i class="fas fa-arrow-left"> </i>
      <% end %>
      <h1 class="date-today my-3"><%= params[:date].to_date.strftime("%b %d") %></h1>
      <%= link_to mood_path(date: (params[:date].to_date + 1)) do %>
        <i class="fas fa-arrow-right"> </i>
      <% end %>
    <% end %>
  </div>

  <div class="emoji">
    <h3>Today you are feeling</h3>
    <div class="emoji_img">
      <div class="<%= @emoji_class %>"></div>
    </div>
  </div>

  <div class="journal">
    <div class="journal_text"><h3>Your daily thoughts</h3></div>
    <p><em>A space for self reflection...</em></p>
    <div class="moon-data">
      <div class="info-card my-3">
      <%= @mood.journal_entry %>
    </div>
    <div class="my-3">
      <%= link_to "Edit Mood", edit_mood_path(date: params[:date]), class: "btn-gradient"  %>
    </div>
  </div>
</div>

<!-- Tabs -->
<%= render "tabs" %>