config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'calendar#day'
  get 'home', to: 'pages#home'

  resource :mood, only: [:new, :create, :edit, :show, :update]
  resolve('Mood') { [:mood] }

  resources :events, only: [:index, :new, :create, :edit, :update, :destroy]

  get 'stats', to: 'pages#stats'
  get 'month', to: 'calendar#month'
  get 'day', to: 'calendar#day'
  get 'set_theme', to: 'application#set_theme'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer py-2 container page">
  <% if user_signed_in? && !devise_controller? && !current_page?(:controller => 'events', :action => 'new') && action_name != "edit" %>
    <div class="navigation" id="nav">
      <%= link_to "Day", day_path(:date => Date.today), class:"btn #{"active" if action_name == "day" || action_name == "show" || action_name == "index" || action_name == "new"}" %>
      <%= link_to "Month", month_path(:date => params[:date]), class:"btn #{"active" if action_name == "month"}" %>
      <%= link_to "Stats", stats_path, class:"btn #{"active" if action_name == "stats"}" %>
    </div>
  <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-dailymoon mx-3">
  <% if user_signed_in? %>
    <%= link_to "/", class: "nav-link" do %>
      Hi, <%= current_user.first_name.capitalize %>! <%= @zodiac_emoji %>
    <% end %>
    <li class="nav-item dropdown">
      <% if cookies[:theme] == "dark" %>
        <%= image_tag "moon5full.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <%= image_tag "moon1new.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to "My Profile", edit_user_registration_path, class: "dropdown-item" %>
        <%= link_to "Sign out", destroy_user_session_path, method: :get, class: "dropdown-item" %>
        <form action="/day" method="get">
          <div class="darkmode dropdown-item">
            <button id="darkmode_on" type="submit" name="theme" value="dark">🌙</button>
            <button id="darkmode_off" type="submit" name="theme" value="light">☀️</button>
          </div>
        </form>
      </div>
    </li>
  <% end %>

  <!-- Stars -->
  <canvas id="canv"></canvas>
  <script>
    var num = 50;
    var radius = 2;
    var max = 250;
    createRandomNodes(50, 2, 250);
    function createRandomNodes(num, radius, max) {
      var canvas = document.getElementById("canv");
      console.log(canvas)
      var context = canvas.getContext("2d");
      context.clearRect(0, 0, canvas.width, canvas.height);
      for (var i = 0; i <=num; i++) {
          context.beginPath();
          var rand_x = Math.random(i) * max;
          var rand_y = Math.random(i) * max;
          context.arc(rand_x, rand_y, radius, 0, 2*Math.PI);
          context.fillStyle = "#ffdc64";
          context.fill();
          context.closePath();
      }
    }
  </script>
</div>