config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'calendar#day'
  get 'home', to: 'pages#home'

  resource :mood, only: [:new, :create, :edit, :show, :update]
  resolve('Mood') { [:mood] }

  resources :events, only: [:index, :new, :create, :edit, :update, :destroy]

  get 'stats', to: 'pages#stats'
  get 'month', to: 'calendar#month'
  get 'day', to: 'calendar#day'
  get 'set_theme', to: 'application#set_theme'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @datetime = DateTime.parse(date_params)
    @events = Event.where(start_time: @datetime.all_day, user_id: current_user.id).order(start_time: :asc)
  end

  def new
    @date = Date.parse(date_params)
    @datetime = DateTime.parse(date_params)
    @event = Event.new(date: @date, start_time: @datetime)
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.date = params[:date]
    @event.start_time = @event.start_time.to_datetime
    @event.end_time = @event.end_time.to_datetime
    if @event.save!
      redirect_to events_path(date: @event.date)
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.assign_attributes(event_params)
    @event.start_time = @event.start_time.to_datetime
    @event.end_time = @event.end_time.to_datetime
    @event.save!
    redirect_to events_path(date: @event.start_time), notice: "Looks good! ✨"
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path(date: params[:date])
  end

  private

  def date_params
    params.require(:date)
  end

  def event_params
    params.require(:event).permit(:title, :start_time, :end_time, :description, :location, :date)
  end
end

app/views/events/_form.html.erb
<div class="container">
  <div class="form-inputs">
    <%= simple_form_for @event do |p| %>
      <%= p.input :title %>
      <%= p.input :start_time, as: :time, default: @event.start_time.utc, :minute_step => 15 %>
      <%= p.input :end_time, as: :time, default: @event.start_time.utc + 60.minutes, :minute_step => 15 %>
      <%= p.input :description, as: :text, :input_html => { :rows => 3 } %>
      <%= p.input :location %>
      <%= p.button :button, "Submit Event", type: "submit", name: "date", value: @date, class: "btn-gradient my-3" %>
    <% end %>
    <%= link_to "Cancel", events_path(date: @event.start_time.to_date) %>
  </div>
</div>

app/views/events/_tabs.html.erb
<div class="container moon-nav">
  <%= link_to day_path(date: params[:date]) do %>
    <i class="fas fa-circle"></i>
  <% end %>

  <% if Mood.where(date: Date.today, user_id: current_user.id) %>
    <%= link_to mood_path(date: params[:date]) do %>
      <i class="fas fa-circle"></i>
    <% end %>
  <% elsif %>
    <%= link_to new_mood_path(date: params[:date]) do %>
      <i class="fas fa-circle"></i>
    <% end %>
  <% end %>
  <i class="fas fa-circle target"></i>
</div>

app/views/events/edit.html.erb
<div class="container page">
  <h1 class="date-today">Make changes to your event:</h1>
  <%= render "form", event: @event %>
</div>

app/views/events/index.html.erb
<div class="container page">
  <div class="cards">
    <div class="date-navigation">
    <% if params[:date] %>
      <%= link_to events_path(date: (params[:date].to_date - 1)) do %>
        <i class="fas fa-arrow-left"> </i>
      <% end %>
      <h1 class="date-today my-3"><%= params[:date].to_date.strftime("%b %d") %></h1>
      <%= link_to events_path(date: (params[:date].to_date + 1)) do %>
        <i class="fas fa-arrow-right"> </i>
      <% end %>
    <% end %>
  </div>
    <% if @events == [] %>
      <p style="text-align: center; margin: 50px 0"><em>You don't have any events planned for today</em></p>
    <% else %>
      <% @events.each do |event| %>
          <div class="info-card my-3 mx-2">
            <%= event.start_time.strftime("%H:%M") %> - <%= event.end_time.strftime("%H:%M") %>
            <h3><%= event.title %></h3>
            <p><%= event.description %></p>
           <div class="edit_btn"> <%= link_to 'Edit', edit_event_path(event) %>
            <%= button_to "Remove",
                              event_path(event, date: params[:date]),
                              method: :delete,
                              data: { confirm: "Are you sure you want to delete this event?"} %>
           </div>
          </div>
      <% end %>
    <% end %>
    <div class="btn-wrapper">
      <div class="my-3">
      <%= link_to "Add Event", new_event_path(date: params[:date]), class: "btn-gradient" %>
    </div>
  </div>

  <!-- Tabs -->
  <%= render "tabs" %>
</div>

app/views/events/new.html.erb
<div class="container page">
  <div class="date-navigation">
    <% if params[:date] %>
      <%= link_to new_event_path(date: (params[:date].to_date - 1)) do %>
        <i class="fas fa-arrow-left"> </i>
      <% end %>
      <h1 class="date-today my-3"><%= params[:date].to_date.strftime("%b %d") %></h1>
      <%= link_to new_event_path(date: (params[:date].to_date + 1)) do %>
        <i class="fas fa-arrow-right"> </i>
      <% end %>
    <% end %>
  </div>
  <%= render "form", event: @event %>
</div>